---
# Commands shared between linux systems

- name: Setup NTP
  include_role:
    name: galaxy_roles/geerlingguy.ntp
  tags: ntp

- name: Install linux packages
  package:
    name: "{{ linux_packages }}"
    state: present

# Ignoring errors because sometimes the pi user has a process in use and I don't want it to fail the whole run
- name: Ensure certain users doesn't exist
  user:
    name: "{{ item }}"
    state: absent
  loop: "{{ linux_users_to_remove }}"
  ignore_errors: yes

- name: Ensure certain  users sudoers file doesn't exist
  file:
    path: /etc/sudoers.d/{{ item }}
    state: absent
  loop: "{{ linux_users_to_remove }}"
  
- name: Ensure {{ linux_admin_user }} exists
  user:
    name: "{{ linux_admin_user }}"
    shell: /usr/bin/fish
    password: "{{ linux_admin_password }}"

- name: Add linux admin user to sudo
  lineinfile:
    path: /etc/sudoers.d/{{ linux_admin_user }}
    line: '{{ linux_admin_user }} ALL=(ALL:ALL) ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Setup fish shell
  include_role: 
    name: galaxy_roles/samdoran.fish
  tags: fish

- name: Include domain join
  include_role:
    name: domain-joined
  tags: domain-joined

- name: Setup telegraf
  include_role:
    name: galaxy_roles/dj-wasabi.telegraf
  tags: telegraf