---
# Commands shared between linux systems

- name: Install linux packages
  package:
    name: "{{ linux_packages }}"
    state: present

- name: Configure ntp
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    backup: yes
  tags: ntp

- name: Start ntp service and ensure it's started automatically
  systemd:
    name: ntp
    state: started
    enabled: yes
    daemon_reload: yes
  tags: ntp

# Ignoring errors because sometimes the pi user has a process in use and I don't want it to fail the whole run
- name: Ensure certain users doesn't exist
  user:
    name: "{{ item }}"
    state: absent
  loop: "{{ linux_users_to_remove }}"
  ignore_errors: yes

- name: Ensure certain  users sudoers file doesn't exist
  file:
    path: /etc/sudoers.d/{{ item }}
    state: absent
  loop: "{{ linux_users_to_remove }}"
  
- name: Ensure {{ linux_admin_user }} exists
  user:
    name: "{{ linux_admin_user }}"
    shell: /usr/bin/fish
    password: "{{ linux_admin_password }}"

- name: Add linux admin user to sudo
  lineinfile:
    path: /etc/sudoers.d/{{ linux_admin_user }}
    line: '{{ linux_admin_user }} ALL=(ALL:ALL) ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'

- name: Set timezone
  timezone:
    name: "{{ timezone }}"