---
# shared vars across all groups

ntpserver: DC1.mcbadass.local
timezone: America/Denver
linux_packages:
  - vim
  - ntp
  - byobu
  - neovim
  - python3
  - python-pip
  - python3-pip

windows_packages:
  - chocolatey

## Fish shell parameters
fish_release_version: 3

## telegraf parameters
telegraf_agent_version: 1.12.6
telegraf_agent_package_method: repo
telegraf_agent_package_state: present
telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["http://docker2.mcbadass.local:8086"]
      - database = "computers"
telegraf_agent_interval: 30
linux_users_to_remove:
  - pi
  - vagrant

# Joey stuff
joey_static_vm_ip: 192.168.70.20


# NTP Settings
ntp_enabled: true
ntp_servers:
  - "{{ ntpserver }}"
ntp_timezone: "{{ timezone }}"