---

all:
  hosts:
  children:
    windows:
      hosts:
        dc2.mcbadass.local:
    dc:
      hosts:
        dc2.mcbadass.local:
    debian:
      hosts:
        tbuntu.mcbadass.local:
        docker2.mcbadass.local: