---

all:
  hosts:
  children:
    windows:
      hosts:
        dc2.mcbadass.local:
    dc:
      hosts:
        dc2.mcbadass.local:
    debian:
      hosts:
        ogpi.mcbadass.local:
        enderpi.mcbadass.local:
        tback.mcbadass.local:
        pz1.mcbadass.local:
        pz2.mcbadass.local:
        web:
        mpsmpi.mcbadass.local:
    raspi:
      hosts:
        ogpi.mcbadass.local:
        enderpi.mcbadass.local:
        tback.mcbadass.local:
        pz1.mcbadass.local:
        pz2.mcbadass.local:
        mpsmpi.mcbadass.local:
    pfsense:
      hosts:
        pfsense.mcbadass.local:
    tvocom:
      hosts:
    cisco:
      hosts:
        192.168.1.251:
    switches:
      hosts:
        192.168.1.251: