---

- name: update the system
  yum:
    name: "*"
    state: latest

- name: Install nfs-utils
  package:
    name: nfs-utils
    state: present

- name: Stop and disable firewalld.
  service:
    name: firewalld
    state: stopped
    enabled: False

- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent
- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  register: swap

- name: Reboot the system
  reboot:
  when: swap.changed