---

- name: Ensure wireguard repo is there
  file:
    path: /etc/apt/sources.list.d/unstable.list
    owner: root
    group: root
    state: touch
  
- name: Ensure wireguard repo is in file
  lineinfile:
    path: /etc/apt/sources.list.d/unstable.list
    regexp: "deb http://deb.debian.org/debian/ unstable main"
    line: "deb http://deb.debian.org/debian/ unstable main"
    state: present

- name: Ensure wireguard unstable preferences are set
  template:
    src: limit-unstable.j2
    dest: /etc/apt/preferences.d/limit-unstable
    owner: root
    group: root
    backup: yes

- name: Install wireguard
  apt:
    name: wireguard
    update_cache: yes

- name: enable IP v4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes