---

- name: Ensure {{ linux_admin_user }} exists
  user:
    name: "{{ joey_admin_user }}"
    shell: /usr/bin/fish
    password: "{{ joey_admin_password }}"

- name: Add linux admin user to sudo
  lineinfile:
    path: /etc/sudoers.d/{{ joey_admin_user }}
    line: '{{ joey_admin_user }} ALL=(ALL:ALL) ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
