---

apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: tvories@gmail.com

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod

    # ACME DNS-01 provider configurations
    solvers:
    - selector: {}
      dns01:
        cloudflare:
          email: tvories@gmail.com
          # !! Remember to create a k8s secret before
          # kubectl create secret generic cloudflare-api-key
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key