---

- name: service config
  ios_config:
    lines:
      - no service pad
      - service timestamps debug uptime
      - service timestamps log uptime
      - service password-encryption

- name: configure jumbo frames
  ios_config:
    lines:
      - system mtu jumbo 9000
  changed_when: false
  
- name: configure timezone
  ios_config:
    lines:
      - clock timezone MST -7 0

- name: config ntp
  ios_ntp:
    server: "{{ ntpserver }}"
    state: present
  changed_when: false

- name: configure snmp-server
  ios_config:
    lines:
      - snmp-server community public RO
      - snmp-server location rack
      - snmp-server contact taylor

- name: configure name servers
  ios_system:
    name_servers:
      - "{{ item }}"
  loop: "{{ nameservers }}"
  changed_when: false

- name: save running to startup when modified
  ios_config:
    save_when: modified