---

# Telegraf specific to raspi
telegraf_plugins_default:
  - plugin: net
  - plugin: kernel
  - plugin: disk
    tags:
      - diskmetrics = "true"
    # tagpass:
    #   - fstype = [ "ext4", "xfs" ]
    #   - path = [ "/opt", "/home" ]
  - plugin: io
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: netstat
  - plugin: processes
  - plugin: file
    config:
      - files = ["/sys/class/thermal/thermal_zone0/temp"]
      - name_override = "cpu_temperature"
      - data_format = "value"
      - data_type = "integer"
  - plugin: exec
    config:
      - commands = ["/opt/vc/bin/vcgencmd measure_temp"]
      - name_override = "gpu_temperature"
      - data_format = "grok"
      - grok_patterns = ["%{NUMBER:value:float}"]
  - plugin: cpu
    config:
      - percpu = true