---
# Playbook for base systems

- name: base profile deployment playbook
  hosts: all
  become: true

  roles:
    - { role: galaxy_roles/samdoran.fish, tags: ['fish']}
    - { role: base, tags: ['base'] }
    - { role: domain-joined, tags: ['domain-joined'] }
    - { role: galaxy_roles/dj-wasabi.telegraf, tags: ['telegraf']}