---

- name: Install Gitlab
  hosts: "gitlab"
  become: true

  roles:
    - role: galaxy_roles/geerlingguy.gitlab
      tags: ['gitlab']
  vars:
    - gitlab_external_url: "https://gitlab.t-vo.us/"
    - gitlab_git_data_dir: "/var/opt/gitlab/git-data"
    - gitlab_backup_path: "/var/opt/gitlab/backups"
    - gitlab_edition: "gitlab-ce"
    - gitlab_nginx_listen_https: "false"
    - gitlab_redirect_http_to_https: "false"
    - gitlab_create_self_signed_cert: "false"
    - gitlab_nginx_listen_port: 8083
    - gitlab_time_zone: "America/Denver"
    - gitlab_backup_keep_time: "604800"
    # - gitlab_download_validate_certs: true
    - gitlab_default_theme: 2
    - gitlab_version: ''

- name: K8 Ingress
  hosts: localhost
  gather_facts: false
  connection: local

  collections:
    - community.kubernetes

  tasks:
    - name: Ensure external k8 service exists.
      k8s:
        namespace: default
        definition:
          api_version: v1
          kind: Service
          metadata:
            name: gitlab
          spec:
            externalName: "192.168.1.92"
            type: ExternalName
        state: present
      tags:
      - k8
    
    - name: Ensure gitlab ingress exists
      k8s:
        namespace: default
        definition:
          apiVersion: extensions/v1beta1
          kind: Ingress
          metadata:
            name: gitlab-ingress
            annotations:
              ingress.kubernetes.io/ssl-redirect: "true"
              kubernetes.io/tls-acme: "true"
              kubernetes.io/ingress.class: nginx-ingress-external
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
              nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For, X-Real-IP, X-Frame-Options, X-Content-Type-Options, X-Forwarded-Proto"
          spec:
            tls:
            - hosts:
              - gitlab.t-vo.us
              secretName: gitlab-t-vo-us
            rules:
            - host: gitlab.t-vo.us
              http:
                paths:
                - backend:
                    serviceName: gitlab
                    servicePort: 8083
          status:
            loadBalancer: {}
        state: present
      tags:
      - k8
