---

- name: K8 Cluster post-terraform
  hosts: k8
  become: true

  roles:
    - { role: base, tags: ['base'] }
    - { role: galaxy_roles/samdoran.fish, tags: ['fish'] }
    - { role: k8s-cluster, tags: ['k8-cluster'] }
